# Generated by Django 3.1.1 on 2020-09-14 05:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(default=datetime.datetime.now)),
                ('photo_main', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
