# Generated by Django 3.1.1 on 2020-09-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='price',
            field=models.IntegerField(default=False),
        ),
    ]
